# Generated by Django 5.0 on 2024-01-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_collections_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collections_saved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.collection'),
        ),
    ]
